<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main box-border">
<?php print_r($args) ?>
                </div>
                <br />
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">

                <!-- /.div -->
                <div class="row">
                    <div class="col-md-2">
                        <div>
                            <a href="#" class="list-group-item active">Electronics</a>
                            <ul class="list-group">

                                <li class="list-group-item">Mobile
                                    <span class="label label-primary pull-right">234</span>
                                </li>
                                <li class="list-group-item">Computers
                                    <span class="label label-success pull-right">34</span>
                                </li>
                                <li class="list-group-item">Tablets
                                    <span class="label label-danger pull-right">4</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <?php for ($i = 1; $i<=5; $i++): ?>
                        <div class="col-md-2 text-center ">
                            <div class="thumbnail product-box">
                                <img src="/img/dummyimg.png" alt="" />
                                <div class="caption">
                                    <h3><a href="#">Samsung Galaxy </a></h3>
                                    <p>Price : <strong>$ 3,45,900</strong>  </p>
                                    <p>Description</p>
                                    <p> <a href="#" class="btn btn-primary" role="button">See Details</a></p>
                                </div>
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>

            </div>
            <!-- /.col -->
        </div>
    </div>

</section>